-- 물고기 종류 별로 가장 큰 물고기의 ID, 물고기 이름, 길이를 출력
WITH MAX_TABLE AS (
    SELECT MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
JOIN MAX_TABLE C ON A.FISH_TYPE = C.FISH_TYPE AND A.LENGTH = C.MAX_LENGTH
ORDER BY ID
