-- 각 아이스크림 성분 타입과 성분 타입에 대한 아이스크림의 총주문량을 총주문량이 작은 순서대로 조회
SELECT I.INGREDIENT_TYPE, SUM(F.TOTAL_ORDER)
FROM ICECREAM_INFO AS I
JOIN FIRST_HALF AS F ON F.FLAVOR = I.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER
